# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

title: Compiler Durden
description: my site
baseurl: ""
url: "https://ubermenchh.github.io"

# Hyde theme via remote_theme
remote_theme: poole/hyde

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Author info (optional)
author:
  name: ubermenchh (Compiler Durden)
  email: ubermenchh69@gmail.com

# Custom vars
version: 2.1.0
