remote-theme: jekyll-dash
title: ubermenchh (Umang Kaushik)
description: my site

# required by disqus to display comments
url: https://ubermenchh.github.io

# for github pages custom domains:
# include: [CNAME]

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: ubermenchh

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://x.com/ubermenchh_
      icon: twitter-square
      color: cyan
    # - url: https://ubermenchh.github.io
    #   icon: 
    #   color: red
    - url: https://github.com/ubermenchh
      icon: github-square
      color: purple

  # wether the author box should be displayed or not
  show_author: true
